title: "Semantic CVC (Commit, Versioning & Changelog)"
description: "A structured approach to commit management, versioning, and changelog generation."
baseurl: ""
theme: jekyll-theme-midnight
custom_css: assets/css/style.css
